import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:wood_cafe/models/menu_model.dart';
import 'package:wood_cafe/routes.dart';
import 'package:dio/dio.dart';
import 'package:dio_http_cache/dio_http_cache.dart';
import 'package:http/http.dart';
import 'package:http/http.dart' as http;
import '../Homepage/onboarding.dart';
import '../checkout/payment.dart';
import 'package:flutter_svg/flutter_svg.dart';

class Text1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 52.3504524230957,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: const [
          Text(
            'Best Rated Meals',
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 23,
            ),
          ),
          Text(
            'See all',
            style: TextStyle(
              color: Colors.red,
              fontSize: 16,
            ),
          )
        ],
      ),
    );
  }
}

/* Group Text
    Autogenerated by FlutLab FTF Generator
  */
class Text3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 335.0,
      height: 52.3504524230957,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: const [
          Text(
            'Best Rated Meals',
            overflow: TextOverflow.visible,
            textAlign: TextAlign.left,
            style: TextStyle(
              height: 1.3333333333333333,
              fontSize: 20.0,
              fontFamily: 'Roboto',
              fontWeight: FontWeight.w900,
              color: Color.fromARGB(255, 1, 15, 7),

              /* letterSpacing: 0.14000000059604645, */
            ),
          ),
          Text(
            'See all',
            overflow: TextOverflow.visible,
            textAlign: TextAlign.right,
            style: TextStyle(
              height: 1.5,
              fontSize: 16.0,
              fontFamily: 'Roboto',
              fontWeight: FontWeight.w400,
              color: Color.fromARGB(255, 235, 1, 0),

              /* letterSpacing: -0.4000000059604645, */
            ),
          ),
        ],
      ),
    );
  }
}

class mediumCard extends StatefulWidget {
  @override
  State<mediumCard> createState() => _mediumCardState();
}

class _mediumCardState extends State<mediumCard> {
  @override
  Widget build(BuildContext context) {
    return InkWell(
        onTap: () {
          Navigator.of(context).pushNamed(PageRoutes.cartPage);
        },
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(20),
              ),
              height: 160,
              width: 200,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(10),
                child: Image.asset(
                  'assets/images/image3.png',
                  fit: BoxFit.contain,
                ),
              ),
            ),
            Text(
              '''English Breakfast''',
              overflow: TextOverflow.visible,
              textAlign: TextAlign.left,
              style: TextStyle(
                height: 1.171875,
                fontSize: 20.0,
                fontFamily: 'Roboto',
                fontWeight: FontWeight.w600,
                color: Color.fromARGB(255, 1, 15, 7),

                /* letterSpacing: 0.4444443881511688, */
              ),
            ),
            Text(
              '''Egg, Sausage, ''',
              overflow: TextOverflow.visible,
              textAlign: TextAlign.left,
              style: TextStyle(
                height: 1.5,
                fontSize: 16.0,
                fontFamily: 'Roboto',
                fontWeight: FontWeight.w400,
                color: Color.fromARGB(255, 134, 134, 134),

                /* letterSpacing: -0.4000000059604645, */
              ),
            ),
            SizedBox(height: 24),
            Container(
              width: 160,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(6),
                        color: Colors.yellow,
                      ),
                      height: 17,
                      width: 34,
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          Icon(Icons.star, color: Colors.white, size: 10),
                          Text(
                            '4.5',
                            style: TextStyle(
                                fontSize: 11,
                                color: Colors.white,
                                fontWeight: FontWeight.w600),
                          )
                        ],
                      )),
                  Icon(Icons.watch_later, size: 16),
                  Row(
                    children: [
                      Text(
                        '20 mins',
                        style: TextStyle(
                          height: 1.5,
                          fontSize: 14.0,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w600,
                          color: Colors.black,

                          /* letterSpacing: -0.4000000059604645, */
                        ),
                      ),
                    ],
                  ),
                  Text(
                    '.',
                    style: TextStyle(
                      height: 1.5,
                      fontSize: 14.0,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w600,
                      color: Colors.black,

                      /* letterSpacing: -0.4000000059604645, */
                    ),
                  ),
                  Text(
                    '#1000',
                    style: TextStyle(
                      height: 1.5,
                      fontSize: 14.0,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w600,
                      color: Colors.black,

                      /* letterSpacing: -0.4000000059604645, */
                    ),
                  )
                ],
              ),
            ),
          ],
        ));
  }
}

/* Group Text
    Autogenerated by FlutLab FTF Generator
  */
class MenuCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
            width: 335,
            height: 185,
            child: Image.asset('assets/images/BG.png')),
        SizedBox(height: 18),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              '''Tuna Melt''',
              overflow: TextOverflow.visible,
              textAlign: TextAlign.left,
              style: TextStyle(
                height: 1.171875,
                fontFamily: 'Roboto',
                fontWeight: FontWeight.w600,
                fontSize: 20,
                color: Color.fromARGB(255, 1, 15, 7),

                /* letterSpacing: 0.4444443881511688, */
              ),
            ),
            Text(
              '''#1000''',
              overflow: TextOverflow.visible,
              textAlign: TextAlign.left,
              style: TextStyle(
                height: 1.171875,
                fontFamily: 'Roboto',
                fontSize: 20,
                fontWeight: FontWeight.w600,
                color: Color.fromARGB(255, 1, 15, 7),

                /* letterSpacing: 0.4444443881511688, */
              ),
            )
          ],
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            Text('Toasted Bread',
                style: TextStyle(
                  height: 1.5,
                  fontSize: 16.0,
                  fontFamily: 'Roboto',
                  fontWeight: FontWeight.w500,
                  color: Color.fromARGB(255, 134, 134, 134),

                  /* letterSpacing: -0.4000000059604645, */
                )),
          ],
        ),
        Container(
          width: 300,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(2),
                    color: Colors.white,
                  ),
                  height: 17,
                  width: 34,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text(
                        '4.5',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.black,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Icon(Icons.star, color: Colors.yellow, size: 12),
                    ],
                  )),
              Row(
                children: [
                  Text(
                    '200+ Ratings',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.black,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  Icon(Icons.watch_later, size: 13),
                  SizedBox(width: 5),
                  Text(
                    '20 mins',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.black,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
              ),
              Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: Text(
                  '.',
                  style: TextStyle(
                    fontSize: 20,
                    color: Colors.black,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Row(
                children: [
                  SvgPicture.asset('assets/svg/Vector.svg'),
                  Text(
                    '#1000',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.black,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
              )
            ],
          ),
        ),
      ],
    );
  }
}
